sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '8'
  - '7'
  - '6'
notifications:
  email:
    recipients:
      - nnsceg@gmail.com
    on_success: never
    on_failure: always
branches:
 except:
   - /^v\d+\.\d+\.\d+$/
before_script:
  - npm prune
scripts:
  - npm run test
  - npm run build
after_success:
  - npm run semantic-release
