sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '7'
  - '6'

test:
  provider: script
  on:
    branch: development

  before_script:
    - npm prune
  scripts:
    - npm run test

deploy:
  notifications:
    email:
      recipients:
        - nnsceg@gmail.com
      on_success: never
      on_failure: always
  on:
    tags: true
    branch: master
  skip_cleanup: true
  before_script:
    - npm prune
  scripts:
    - npm run test
    - npm run build
  after_success:
    - NPM_TOKEN=$NPM_TOKEN npm run semantic-release
